variables:
  DOCKER_DRIVER: overlay

cache:
  # cache per branch:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules
    - bower_components

# normal build job:
build:
  except:
    - master
  image: node:9.0.0
  script:
    # Temporary test:
    - if [ ! -z $(git status -s) ]
      then
        echo 'This build changed a file. Please ensure you configure your environment to use only Unix-style line endings, 
        and remember to commit changes to the dist directory.'
        echo 'git status says'
        git status
        exit 1
      fi
    - npm run build
    - if [ ! -z $(git status -s) ]
      then
        echo 'This build changed a file. Please ensure you configure your environment to use only Unix-style line endings, 
        and remember to commit changes to the dist directory.'
        echo 'git status says'
        git status
        exit 1
      fi
